### ISSUE TITLE
Static map integration

### ISSUE THREAD

**Issue by MartinMeyerTP** [MartinMeyerTP/capstone-project#1]
## Value Statement
As a **user**
I need to see **a map** 
so that I can see **the main part of the app**

## Description 
The main part of the app 

## Acceptance criteria
- [x] Implement the map to the app, to be shown

## Tasks
- [x] create map with mapbox
- [x] get the access token 
- [x] write map component 
- [x] set viewport and mapstyle 

## Size
small
