### ISSUE TITLE
Set viewport to map

### ISSUE THREAD

**Issue by MartinMeyerTP** [MartinMeyerTP/capstone-project#2]
## Value Statement
As a **user**
I need to **change the maps viewport** 
so that I can **navigate on the map**

## Description 
set a state that can change the map's viewport

## Acceptance criteria
- [ ] Implement state to scroll on the map 

## Tasks
- [ ] set a state viewport
- [ ] implement setViewport to Map
- [ ] implement map component to app   

## Size
medium
