### ISSUE TITLE
Get user Position 

### ISSUE THREAD

**Issue by MartinMeyerTP** [MartinMeyerTP/capstone-project#3]
## Value statement
As a **user** 
I need **user Position** 
so that **I can see my position on the map** 

## Description
Localize user Position automatically when the map is mounted

## Acceptance criteria
- [ ] use userPosition state to save Position on the map
- [ ] use useEffect to show Position when map is mounted

## Tasks
- [ ] write new component UserPosition Pin 
- [ ] set userPosition as a state
- [ ] write useEffect hook to set Position when Map is mounted
- [ ] write getUserPosition function to set the position on the map 

## Size
medium
