### ISSUE TITLE
First styling

### ISSUE THREAD

**Issue by MartinMeyerTP** [MartinMeyerTP/capstone-project#4]
## Value statement - a requirement, not a solution
As a **user** 
I need **a basic styling** 
so that **the app looks acceptable on the first look** 

## Description 
 - Add stylings here

## Acceptance criteria
- [ ] First Grid and styling for Prototype 

## Tasks
- [ ] Research first styling components
- [ ] Style main components (header, main) with Sketch
- [ ] Install styled-components and write GlobalStyles
- [ ] Implement Prototype Styles from Sketch into App

## Size
large
