### ISSUE TITLE
Set Pins on map 

### ISSUE THREAD

**Issue by MartinMeyerTP** [MartinMeyerTP/capstone-project#5]
## Value statement - a requirement, not a solution
As a **user** 
I need **to set a pin** 
so that **I can get started for the apps main usage** 

## Description 
Set a Pin on the map ans save it

## Acceptance criteria
- [ ] pin should be set with left-mouse-click on the map 
- [ ] pin should be drag- and dropable until the state is set
- [ ] pin should have a different style in relation to the user Pin
- [ ] pin should be ready to get more functionality 
- [ ] pin should have a state to be saved for more usage 

## Tasks
- [ ] write new component "DraftPin"
- [ ] style Pin component with props 
- [ ] write set Pin functionality 
- [ ] implement animated pun
- [ ] set Pin to state

## Size
medium
