### ISSUE TITLE
Stories with storybook 

### ISSUE THREAD

**Issue by MartinMeyerTP** [MartinMeyerTP/capstone-project#6]
## Value statement - a requirement, not a solution
As a **client** 
I need **storyboard** 
so that **I can choose between different styles** 

## Description
Writing first stories for main and secondary components for implementing first design sheets

## Acceptance criteria
- [ ] storybook must be setted up 
- [ ] components must be implemented to storybook 
- [ ] components must be ready for storybook setup 

## Tasks
- [ ] make setup 
- [ ] write component stories
- [ ] implement style-sheets from sketch
- [ ] commit first stylings

## Size
medium
