### ISSUE TITLE
Header component

### ISSUE THREAD

**Issue by MartinMeyerTP** [MartinMeyerTP/capstone-project#7]
## Value statement - a requirement, not a solution
As a **user** 
I need **a Header component** 
so that **the app looks like an app** 

## Description
First styling and implementation for a header component

## Acceptance criteria
- [ ] header must be compatible with every page
- [ ] header must be styleable via props
- [ ] header children must be set on different pages
- [ ] header shall contain a hamburger on every page

## Tasks
- [ ] create header component
- [ ] add basic styling 
- [ ] add children properties
- [ ] implement header to first page

## Size
small
