### ISSUE TITLE
Create area // Create page

### ISSUE THREAD

**Issue by MartinMeyerTP** [MartinMeyerTP/capstone-project#9]
## Value statement - a requirement, not a solution
As a **user** 
I need **a functionality for the pins** 
so that ** I can create a game component** 

## Description 
An area that shows the different functionalities for the setted pins on the map. 

## Acceptance criteria
- [ ] Should be on the creation page
- [ ] Should be toggleable from the bottom 
- [ ] The toggled area should show the actual Pin 
- [ ] The Area should contain the following functionalities:
       - [ ] Title Input
       - [ ] checkbox if it's a waypoint or event
       - [ ] congratulation textarea
       - [ ] textarea to show the new task
       - [ ] some space to add more functionalities
- [ ] the area should get a first design 
- [ ] should show different content if a pin is clicked 

## Tasks
- [ ] implement create page
- [ ] write toggle hook and set toggle state
- [ ] set first styling
- [ ] write form components to area
- [ ] write function to show the actual content of the pin

## Size
large
